# We start from a uv image to make life easier.
FROM materialsvirtuallab/lammps_gnnp:latest

ENV DGLBACKEND=pytorch

RUN uv pip install --system dgl==2.1.0 torch==2.2.0 torchdata==0.7.1
RUN uv pip install --system matgl==1.2.6 matcalc==0.3.3 matpes
