name: Docker Hub Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./
          file: docker/Dockerfile.lammps.ml
          push: true
          tags: materialsvirtuallab/lammps:latest-ml
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
